### ISSUE TITLE
Add sass-list-maps as a setting

### ISSUE THREAD

**Issue by JesseBilsten** [jking90/docpad-plugin-nodesass#18]
https://github.com/lunelson/sass-list-maps

A setting like Bourbon and Neat would be fantastic.

### style.css.scss
```scss
...
@import "sass-list-maps";
...
```

### docpad.coffee
```coffeescript
...
plugins:
  nodesass:
    listMap: true
...
```

**Comment by jking90** [comment]
Any progress on this @JesseBilsten?

**Comment by JesseBilsten** [comment]
This completely fell off my radar although since you pinged me, I'll try and add it back on. If anyone else has the time, feel free to pick it up. I've been swamped with regular work lately and haven't had a chance to pick up my side projects.
