### ISSUE TITLE
Update node-sass to v1.0.1

### ISSUE THREAD

**Issue by jking90** [jking90/docpad-plugin-nodesass#19]
https://github.com/sass/node-sass/releases/tag/v1.0.1

**Comment by karlis-upitis** [comment]
For new features I updated *package.json* dependencies to these:

```javascript
"dependencies": {
    "taskgroup": "~3.4.0",
    "node-sass": "~1.2.3",
    "node-bourbon": "~1.2.3",
    "node-neat": "~1.4.2"
  }
```
Although node-sass now has version 2.0.0-beta, decided to use stable version.

**Comment by jking90** [comment]
@karlis-upitis Would you submit an update pull request?

**Comment by jking90** [comment]
v2.5.0 updated to 1.2.3
