### ISSUE TITLE
merging in include-once?

### ISSUE THREAD

**Issue by nfriedly** [jking90/docpad-plugin-nodesass#35]
Hey, I forked this to create https://github.com/nfriedly/docpad-plugin-nodesassimportonce because I though it would be a fairly involved conversion. However it looks like I could have gotten my actual need met with just this module and a bit of configuration, so, I think I'm going to kill mine and just point to this one.

That said, I thought I'd offer to make a PR with include-once as a boolean config option or alternatively just an example that shows how to wire it up without any changes to this lib. Would you be interested in either of those?

Also, I made everything fully asynchronous in my fork, would you like that change included in the PR as well?

**Comment by nfriedly** [comment]
Oh, and I should probably link to the actual plugin: https://www.npmjs.com/package/node-sass-import-once

**Comment by jking90** [comment]
Do you think it would provide significantly more value to include it as an option than to provide an implementation example? For instance, I don't think that the bourbon and neat options provide enough value over implementing them through other configuration, and wouldn't put them in if I could go back. But I can't remove them now without breaking some projects.

**Comment by nfriedly** [comment]
Aah, that's a fair point then. I was somewhat thinking "follow the leader" and suggesting having it built-in to match bourbon & neat. But if you'd rather not even have the current built-in options, then we probably don't want this one built-in either.

(And, outside of DocPad, I would say just remove them and bump the major version... but I think you're kind of stuck now.)

How about a PR with an example in the readme for using import-once, and then the async changes?

**Comment by jking90** [comment]
Sounds good.

Maybe I'll deprecate them and leave them in with a warning log for a few months.
