### ISSUE TITLE
Cannot install on OSX

### ISSUE THREAD

**Issue by maciejmyslinski** [jking90/docpad-plugin-nodesass#63]
On OS X i get an error
```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.0/darwin-x64-47_binding.node":

HTTP error 404 Not Found
```

and hundreds other errors and warnings.

**Comment by jking90** [comment]
I was unable to reproduce your issue, but it sounds like it may have been a problem with the targeted version of node-sass. I have just published a new version with updated dependencies. Let me know if that fixes it for you.

**Comment by maciejmyslinski** [comment]
@jking90 now works like a harm. Thanks!
